name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        operating: [ubuntu-latest, windows-latest]
        node-version: [12, 14, 16]
        # 1. include specific version to specify the operating system
        include:
          - node-version: 18
            operating-system: ubuntu-latest

        # 2. exclude specific version to specify the operating system
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
