name: First Workflow
on: workflow_dispatch # trigger workflow manually
jobs:
  first-job:
    runs-on: ubuntu-latest # host runner
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Goodbye World"
