/*
  Understanding Job Artifacts
  - Artifacts are a list of files and directories that are generated by the job execution and are passed between jobs
    -> build app job -> return list of files that we want to use to deploy to the hosting provider 

  - we starts with a basic workflow -> check 01-starter -> <demo.yml>


\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

  Uploading Job Artifacts
  - our project 
    -> build step will produces a list of files 
    -> deploy step will need to access to those files

      <build>:
        steps:
          ...
          - <name>: Build website
            run: npm run build
      <deploy>:
        needs: build
        ...


----------------------------

  - Upload Artifacts Action: https://github.com/actions/upload-artifact
  - to store those artifacts -> add new step

      <build>:
        steps:
          - <name>: Build website
            run: npm run build
          - <name>: Upload artifact
            uses: actions/upload-artifact@v3
            with:
              <name>: dist-files
              <path>: dist

  - multiple ways to work with path
    # single path
        path: path/to/artifact/world.txt

    # multiple paths
        path: |
          path/output/bin/
          path/output/test-results
          !path/output/test-results/*.xml -> 🌲 exclude this path


\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

  Downloading Artifacts (Manually & Automatically)
  - https://github.com/actions/download-artifact

      deploy:
        <needs>: build
        runs-on: ubuntu-latest
        steps:
          - <name>: Get build artifact
            <uses>: actions/download-artifact@v3
            <with>:
              <name>: dist-files
          - <name>: Output contents
            <run>: ls
          - name: Deploy
            run: echo "Deploying..."



*/
